
CREATE SCHEMA IF NOT EXISTS ping_pulse;

CREATE TYPE host_status AS ENUM ('UP', 'PENDING', 'DOWN', 'UNREACHABLE', 'MAINTENANCE');
CREATE TYPE alarm_status AS ENUM ('PENDING', 'ACKNOWLEDGED', 'RESOLVED');
